name: Publish GitHub release
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Create the rootfs
        run: |
          sh ${{ github.workspace }}/build-rootfs.sh

      - name: Create the GH release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/artifacts/*
          tag_name: ${{ github.sha }}
