name: Publish GitHub release
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Get the short version of the last commit
        id: vars
        run: echo "tag_name=$(date +"%Y.%m.%d").$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Check if the image needs update
        id: needs_update
        run: ${{ github.workspace }}/scripts/check-for-update.sh

      - name: Create the rootfs
        if: contains(steps.needs_update.outputs.stdout, 'rebuild is needed')
        run: |
          ${{ github.workspace }}/build-rootfs.sh

      - name: Create the GH release
        if: contains(steps.needs_update.outputs.stdout, 'rebuild is needed')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/artifacts/*
          tag_name: ${{ steps.vars.outputs.tag_name }}

